### ISSUE TITLE
Study of already available JSON editors

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#1]
There are 2 JSON editors available which are in active development on Github and seem to be popular.

Here's the some (high level) info about both of them:

### General info
- Schema validation support
- Json syntax validation support
- Uses `require.js`
- Good code documentation (`jsdoc` like)
- Not really fast to navigate with TAB, but can be fixed by skipping some html elements while tabbing
- `gulp.js` is used for (build) tasks
- `uglify-js` is used to minify js code
- `mocha` for running unit tests
- Can be used in angular apps (has a wrapper angular module)
- Written in plain javascript (not ES6) and uses some css
- Uses `webpack` to package stuff
- More control to user/editor (lower level editing that requires a little bit of understanding of JSON syntax)

### Overview of first demo

For large JSON documents, scrolling is too slow and not smooth  to work with at all.

#### Possible solutions to drawbacks above

(Not sure, if it is possible) A [Clusterize](http://clusterize.js.org/)-like tool/method could be used to improve performance.

### General Info

- **Better** schema validation support
- `grunt.js` is used for (build) tasks, including uglifying
- Can be used in angular apps (has a wrapper angular module)
- Written in plain javascript (not ES6) and supports different css frameworks (`bootstrap`, `foundation`, `jqueryui` etc.)
- Generates html form, users/editors have no idea if they are editing a json document
- More and easily configurable with small changes but more difficult (I guess) to change something because code base is relatively large
- Supports external editors which are suitable for particular kinds of fields. For instance if a field is to be an html code, it can be edited via SCEditor (a WYSIWYG Html editor).

### Overview of first demo

Although scrolling is smooth enough (not for docs with 2000+ authors), form generation and rendering is time more than 15-20 seconds. And with default configurations, it doesn't look compact for large JSON documents.

#### Possible solutions to drawbacks above

- Generates single text-area or simpler text-boxes for some fields like references and authors.
 - Inside the text-area, each tab can focus the next element of array.
  - **This solution only valid for string arrays, not object arrays which are mostly larger. [selectize.js](http://selectize.github.io/selectize.js/) was tried, good UI, same performance**
- Use simpler CSS frameworks.
- Divide the form into multiple pages or render/generate large (array type) fields when they are expanded on the UI.
 - **It gets little faster but still when a large array field expanded, it freezes and scrolling becomes less smooth**
- Paginate large array fields.
 - **Limiting arrays (authors and references) to 10 elements is reduced rendering/generation time to several seconds**

### "Problems" in source code

- Generally more complex than it should be for such tool, so it is difficult to modify existing features or add a new one.
- It serializes (`JSON.stringify`) all new value then check with existing value serialization to decide if any element changed or not?
  - There is not even length check before in order to avoid serialization when a new element added or removed.
- It updates all values of array, even if one of them changed, removed or added.
- It generates duplicates of pop-up `Properties` edit form per array element. 
- It seems to be very difficult to make generated form look like BibEdit UI.

**Comment by eamonnmag** [comment]
Cool. See http://e-monocot.org/taxon/urn:kew.org:wcs:taxon:449127 for the scrollspy implementation which can work well for navigating to different sections on the editor.
