### ISSUE TITLE
Allow file management

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#104]
When a user submits a suggestion, a new entry is created in the Holding Pen.

Now one can open the JSON editor from the Holding Pen, so we should add a feature that will allow to add PDFs to the record.

This would be save a lot of time to the person approving the suggestion, since all the needed actions can be done before approval and the rest of the automated processes will then happen on inspirehep.net side.

**Comment by harunurhan** [comment]
@jmartinm Can you explain this a bit more, I don't think it's clear enough to me.

**Comment by harunurhan** [comment]
@jmartinm I just realized this, does this has to be done before the first release?
