### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#106]
Basic e2e tests need to be added. Minimum to start can be:

* [ ] Open different types of records: literature, authors, conferences, ... and make sure the elements are on the page. Example different types of documents are available in https://github.com/inspirehep/inspire-schemas/tree/master/tests/integration/fixtures. They are missing `$schema` field. It needs to be added pointing to the appropriate schema (https://cernbox.cern.ch/index.php/s/Ouuokl6vlBfQXPf)
* [ ] Test that /holdingpen component works.

**Comment by zzacharo** [comment]
@jmartinm Work on this one before #108?

**Comment by jmartinm** [comment]
Yes, let's put this e2e tests in place first.

**Comment by jmartinm** [comment]
Moved to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/162
