### ISSUE TITLE
Custom validation on Save

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#108]
Here is a list of validators that can be implemented https://github.com/inveniosoftware-contrib/invenio-record-editor/issues/9

We can implement those validators and the view that the editor will call on Save in the `inspirehep-next` repo (https://github.com/inspirehep/inspire-next/tree/master/inspirehep/modules). Create a new module editor there.

A view of all the errors and warnings needs to be available on the left panel (similar to the screenshot below):

<img width="448" alt="screen shot 2017-01-26 at 7 48 32 pm" src="https://cloud.githubusercontent.com/assets/580727/22347641/a20c7640-e400-11e6-8338-61ae893ccd3e.png">

Clicking on the error/warning will move the editor to the appropriate field.

**Comment by harunurhan** [comment]
Error panel will be part of `ng2-json-editor` right? @jmartinm

**Comment by jmartinm** [comment]
> Error panel will be part of ng2-json-editor right? @jmartinm

Yes, that's right.

**Comment by StellaCh** [comment]
Closing this as it's resolved but feel free to open it again if that's not the case @harunurhan
