### ISSUE TITLE
Configuration improvements

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#112]
To make writing configuration easier, some improvements to be made:

* Make `priority` an array. It will appear in a parent object and refer to the keys inside. For example:

```javascript
'abstracts': {
    priority: ['value', 'source']
}
```

(we might consider doing this for other config options as well, like `alwaysShow` although in those cases order is not important)

* If it does not cause any problem, we can skip `items` and `properties` keywords and add logic that finds the correct key.

* When record changes a certain value (for us `document_type`) - reload config

**Comment by jmartinm** [comment]
CC @harunurhan @michamos

**Comment by harunurhan** [comment]
@jmartinm should we move this to [inveniosoftware-contrib/ng2-json-editor](https://github.com/inveniosoftware-contrib/ng2-json-editor) ?

**Comment by jmartinm** [comment]
I was wondering if all of them can be done in `ng2-json-editor` or the last one we need to do in `record-editor` with a callback after field is changed to change config.
