### ISSUE TITLE
When entering author subject areas, you can create duplicates

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#122]
Moved from https://github.com/inspirehep/inspire-next/issues/2094

And those duplicates are then saved into the record:

![screenshot from 2017-03-21 21-29-40](https://cloud.githubusercontent.com/assets/587148/24169320/83760b22-0e7d-11e7-97a4-b7c5ddbe2d66.png)
![screenshot from 2017-03-21 21-29-26](https://cloud.githubusercontent.com/assets/587148/24169323/8511ce26-0e7d-11e7-9d25-9a79713feeb5.png)

Related to https://github.com/inspirehep/record-editor/issues/121

**Comment by harunurhan** [comment]
this happens because schema validation (`"uniqueItems": true` in this case) is still in progress, closing https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/182 will fix this kind of issues.
