### ISSUE TITLE
Create splash page in /record/editor

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#125]
When accessing `/record/editor` a splash page should be presented. It should be similar to:

<img width="722" alt="screen shot 2017-03-27 at 4 17 54 pm" src="https://cloud.githubusercontent.com/assets/580727/24360960/ff66f018-1308-11e7-9d45-4a6a82389e72.png">

* For creating a new record there should be one option per document type: Literature, Author, Conference and so on. Based on the type selected, the API that we be do the final `PUT` request should change to the appropriate `/api/literature`, `/api/authors`, ....

* For literature there should be as well the option of creating one of the subtypes (from [jsonEditorConfigs](https://github.com/inspirehep/record-editor/blob/master/src/app/app-config.service.ts#L11))

* We can see later if add already the option of importing from sources to create new records.

**Comment by harunurhan** [comment]
(almost) duplicate #107
