### ISSUE TITLE
Configuration based on user tests

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#131]
1. Title: Make title bigger and source smaller. Same for abstracts
2.  Inspire category : value first
3.  Collaboration: always shown
4.  Reordering: hide the buttons ↑↓ on the right
5.  Refereed should be a toggle, as it's a boolean
6.  Authors: 
- the affiliation should be always shown, with a pull down 
- in all ids the value should be first.
7.  Urls: 
- Hide the inspirehep.net stuff and .png by default 
- value first

**Comment by harunurhan** [comment]
@StellaCh there is no `value` in `inspire_categories`? you meant `term` I guess?

**Comment by harunurhan** [comment]
@StellaCh  for the 3. you menat `collaborations` top level field?

**Comment by harunurhan** [comment]
4. will be fixed with the new release we just need to enable them for `references` and `authors` by setting `sortable: true`

**Comment by harunurhan** [comment]
7., first bullet point is not supported yet. It's a new feature that we must consider (disabling/hiding by content of field), But I remember we were consindering the put those `.png`s to some other field and and hide it :)

**Comment by StellaCh** [comment]
Yes to questions for (2) and (3). 
For (7), whatever makes more sense to you for the implementation. From a user point of view, they are not interested in seeing or editing these items in the record editor.
