### ISSUE TITLE
show number of unlinked references

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#148]
Currently, curators don't know how many references they have to correct in the references tab resulting in them searching in all the pages.

Add a label to show how many unlinked references there are (2 out of 31), as:
<img width="491" alt="screen shot 2017-07-27 at 10 00 35" src="https://user-images.githubusercontent.com/24955201/28660242-8bb0275c-72b2-11e7-83ba-9d1761a75fd6.png">

Add also a switch to select whether you also want to show all references or only the unlinked ones that need curation. The option 'To link' should be the default.

**Comment by harunurhan** [comment]
Should be closed after https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/359 is merged
