### ISSUE TITLE
display X in error panel

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#149]
The icon to close the record panel has disappeared from the top left corner, although clicking on the area correctly closes it. 
 ![error-panel](https://user-images.githubusercontent.com/24955201/27376884-b331f36a-5673-11e7-8d84-310e15d923c2.PNG)

**Comment by zzacharo** [comment]
Issue appears in `qa` environment.

**Comment by jmartinm** [comment]
Fixed
