### ISSUE TITLE
Hide files field

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#152]
The files field should be hidden from the UI since it has internal information that should not be modified by hand.

<img width="843" alt="screen shot 2017-06-26 at 6 22 52 pm" src="https://user-images.githubusercontent.com/580727/27549523-822db024-5a9c-11e7-8703-07cfa3674e97.png">

**Comment by michamos** [comment]
not so sure about this, it depends on how we end up managing files, both at the backend and UI level.

**Comment by michamos** [comment]
indeed, `_files` can be hidden.
