### ISSUE TITLE
Add pagination in references

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#156]
When we are in the bottom of the References pages, there's no possibility to go to the next page unless we scroll up. Curators should be able to go to the next page without having to scroll up. 
There are 2 possible solutions to this:
- Add pagination also at the end of each References page.
- Or make the top pagination sticky

<img width="181" alt="screen shot 2017-07-20 at 09 10 30" src="https://user-images.githubusercontent.com/24955201/28405021-dc31d73e-6d2b-11e7-85bb-75e0409ea3cc.png">

**Comment by harunurhan** [comment]
I am sure they have their reasons to request this, but gonna leave this beautiful answer here

https://stackoverflow.com/a/25036971/2452467

**Comment by StellaCh** [comment]
Was this comment meant for another issue? :p

**Comment by harunurhan** [comment]
yes 😄

**Comment by harunurhan** [comment]
Fixed by https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/334
