### ISSUE TITLE
Open pdf in new window

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#157]
When curators click on the link of the pdf (or arXiv) in the preview screen, they would like to open it in a new window, instead of a new tab that it is currently
 <img width="154" alt="screen shot 2017-07-20 at 09 24 20" src="https://user-images.githubusercontent.com/24955201/28405631-a856730a-6d2d-11e7-9534-4be92cbe368b.png">

**Comment by harunurhan** [comment]
I am sure they have their reasons to request this, but gonna leave this beautiful answer here

https://stackoverflow.com/a/25036971/2452467

**Comment by StellaCh** [comment]
This was requested by several users from DESY, Fermilab and SLAC.
I generally agree with opening links in new tabs rather than windows, but this case is different. Most (if not all) of the curators have 2 screens, so they'd like to see the pdf on their second screen. Every time they used this functionality, they were moving the pdf from a tab to a new window, so opening it directly to a new window, will save them a click

**Comment by harunurhan** [comment]
Fixed by https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/342
