### ISSUE TITLE
Increase number of references per page

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#158]
Increase the number of references per page to 50.
Users want to have as many as possible (if not all) in one page

**Comment by harunurhan** [comment]
this is gonna cause performance problems if they aren't linked.

**Comment by StellaCh** [comment]
As discussed, let's try with 50 and see if we need to decrease the number due to performace issues

**Comment by harunurhan** [comment]
I tried a bit, and if all 50 is not linked then is slightly slow so I am settling down to 40.
