### ISSUE TITLE
LaTeX in Chrome

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#159]
When in Chrome , the LaTeX in the abstract doesn't appear correctly: 

https://qa.inspirehep.net/editor/literature/1605151 

![latex](https://user-images.githubusercontent.com/24955201/28213346-f0879b18-68a5-11e7-91b1-bcbb7840ff17.PNG)

In Firefox, it works fine.

**Comment by harunurhan** [comment]
This weird, I think it could be because of `prod` bundling or page styles could be breaking the LaTeX modules styles. Because this works locally on Chrome.

![screen shot 2017-07-21 at 15 17 40](https://user-images.githubusercontent.com/4868667/28464946-6ef3838c-6e27-11e7-936e-e42192dac377.png)

**Comment by jmartinm** [comment]
The link above works. Might have been a temporary problem on QA.
