### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#161]
- [x] publication info always show: page_start
- [ ] modify config for disabled fields: you can't delete, add or order any disabled field 
- [x] the field '/dois/items/properties/value' should not be disabled.
- [x] autocompletion in affiliations

**Comment by harunurhan** [comment]
@StellaCh  can you check https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/254#issuecomment-316996507 for disabled fields.

**Comment by harunurhan** [comment]
the last remaining item is something `ng2-json-editor` doesn't have at the moment. If the requirement is certain, I will create an issue there implement a new configuration for this

@StellaCh

**Comment by StellaCh** [comment]
I modified the remaining item, so it only depends on: https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/254

**Comment by harunurhan** [comment]
Closing this, we can track the last thing in inveniosoftware-contrib/ng2-json-editor#254
