### ISSUE TITLE
Add tooltip with MARC description

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#165]
To make the transition from MARC to JSON smoother,  when hovering over a label, add a tooltip with the corresponding MARC number.

**Comment by jmartinm** [comment]
The MARC code can be extracted from the description in the schema - see https://github.com/inspirehep/inspire-schemas/blob/master/inspire_schemas/records/hep.yml#L205

**Comment by harunurhan** [comment]
I am gonna leave this open to keep track of the milestone but actual issue is here:
https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/337 where we can also discuss more.

**Comment by harunurhan** [comment]
@StellaCh can you check the content of `schema.description` with curators to see if it's more helpful for them to see the whole content or just `MARC` field equivalent?
