### ISSUE TITLE
Extracting references

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#166]
Add the option to run refextract in References

Refextract can be triggered when clicking on glyphicon glyphicon-list-alt:

<img width="641" alt="screen shot 2017-07-25 at 12 07 24" src="https://user-images.githubusercontent.com/24955201/28567200-dfa321ca-7131-11e7-97d7-2c02702e8b88.png">

**Comment by harunurhan** [comment]
Possible after https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/341 is merged.

**Comment by StellaCh** [comment]
The UI for the modals should be exactly the same as in the existing system.
When clicking the opion ' Extract references from text':
![refs](https://user-images.githubusercontent.com/24955201/29362676-306058dc-828d-11e7-9343-b3d286be3118.PNG)

When clicking the option 'Extracting references from URL':
![refs-url](https://user-images.githubusercontent.com/24955201/29362677-319e169e-828d-11e7-84ba-ca16a969cad0.PNG)
