### ISSUE TITLE
UI should support keyboard navigation

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#18]
All input elements should be navigable by arrows key.

**Comment by kaplun** [comment]
As mentioned IRL, could be also good to have sort of `Shif-down/up` to move e.g. from affiliation in a given author to the affiliation of the next author.

**Comment by kaplun** [comment]
You might want to take inspiration also from the legacy short-cuts: https://inspirehep.net/help/admin/bibedit-admin-guide#2

so that if possible cataloguers will feel at home.

**Comment by harunurhan** [comment]
#19 edited to include this issue.
