### ISSUE TITLE
Notification users incase of error/warning/info for http requests

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#182]
I think it's good to show user a little bit of information when we the record loading or tickets etc and also notify them if any request is failed.

### When

- ~~record is loading: `Record is loading...`~~
- ~~tickets are loading: `Tickets are loading...`~~
- record failed: `Couldn't load the record!`
- tickets failed: `Couldn't load the tickets!`
- tickets no permission: `Logged in user can not access to tickets`
- extracting references: `Extreacting references...`
- references extracted: ` N references are extracted successfully`

#### v2
(after #192 is merged)
- reverting: `Reverting record to revision: <date>`
- reverting done: `Record is to revision: <date>, now you can edit`

(Please add more or remove if you have something in mind @StellaCh @jmartinm )

### UI

We could use https://github.com/scttcper/ngx-toastr for toast notifications

**Comment by jmartinm** [comment]
Also when getting the record and saving the record, `GET` and `PUT` requests it might happen that the user does not have permissions. We can show a message for that.

After extracting references it might also be good to show 'Extracting references...'

**Comment by StellaCh** [comment]
Yes, DESY also requested an 'Extracting References' message. Could be with a spinner.

A similar message 'Record is locked by user XXX' should be shown when someone tries to access the record but it is locked by someone else, see https://github.com/inspirehep/record-editor/issues/110

**Comment by harunurhan** [comment]
updated the list, @jmartinm  @StellaCh

**Comment by StellaCh** [comment]
> reverting: Reverting record to revision: <date>

This description is not clear. What does it mean?
