### ISSUE TITLE
Add manual configuration (document type) selection support to UI 

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#183]
Now we load the correct configuration based on the `$schema` and if it's hep we merge `default` config with the config for `document_type`.

But we can also have a dropdown or similar, somewhere on the UI so that user can pick choose the document type if it's hep record.

would that be useful @michamos? if yes, do you have an opinion for the UI @StellaCh

**Comment by michamos** [comment]
Not sure I understand. Cannot you already add stuff to `document_type` in the record? why do you need an extra dropdown?

**Comment by harunurhan** [comment]
@michamos yeah you're right!

I thought you might want a separate thing but ok then what I am gonna do is that change the config as you change `document_type` on record.

**Comment by StellaCh** [comment]
I created a document to define the configuration: https://docs.google.com/document/d/14z0O_IPGA_ATq7JLruSTtV3cRL4A_UfWkEIi7W3rJHo/edit#heading=h.9fn1cujyz5lg 
@michamos can you please fill it in involving the other curators if necessary? Thanks
