### ISSUE TITLE
Configurable keyboard shortcut support

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#19]
The editor should have useful keyboard shortcuts for record navigation and other functionalities.

Also It should be possible to overwrite default shortcuts for available actions via a configuration file (json or yaml).

This kind of library might be useful https://github.com/brtnshrdr/angular2-hotkeys

### List of shortcut actions

- All in https://inspirehep.net/help/admin/bibedit-admin-guide#2  (from #18)

**TO BE ADDED MORE**

**Comment by jmartinm** [comment]
@harunurhan can you merge with https://github.com/inspirehep/record-editor/issues/18

**Comment by harunurhan** [comment]
I was doing some initial work this issue and using https://github.com/brtnshrdr/angular2-hotkeys which is based on https://github.com/ccampbell/mousetrap, and had annoying performance drop.

You can have a look two gifs

### Before angular2-hotkeys

![without-hotkeys](https://cloud.githubusercontent.com/assets/4868667/18055368/cef0790a-6e07-11e6-9e6d-b6a70eaeb371.gif)

### After angular2-hotkeys 

![with-hotkeys](https://cloud.githubusercontent.com/assets/4868667/18055456/34760fd8-6e08-11e6-8c7a-0b4c7ce71763.gif)

I haven't investigated much about what is causing this, @eamonnmag maybe you have an idea since (AFAIK) you have used a the `angular1.x` version of this before.

**Comment by kaplun** [comment]
Woah that is really a performance impact. I guess the fan is also twisting...

**Comment by harunurhan** [comment]
Issue moved to [inspirehep/ng2-json-editor #4](https://github.com/inspirehep/ng2-json-editor/issues/4) via [**ZenHub**](https://www.zenhub.com/)
