### ISSUE TITLE
Add $$ splitting to all fields

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#197]
Currently, based on https://github.com/inspirehep/record-editor/pull/150 , we can use the $$ shortcuts only in the 'misc' field. 
SLAC and CERN requested to add the possibility to split fields with $$ in all fields of the reference, not only the 'misc' field.
Also, after you split the 'misc' field and it is empty, it should be hidden from the interface.

**Comment by harunurhan** [comment]
All necessary work done but I need to know list of fields in reference to make splittable as we discussed not to do it for all. @StellaCh

**Comment by StellaCh** [comment]
Most of the fields that have a $$ shortcut should be included, here is the list: 

['title', 'title'],  		
['publication_info', 'journal_title'], 	                                                                            
['dois'], 			
['collaborations'], 		
['isbn'], 			 										
['report number'], 		
['arxiv_eprint'], 			
['publication_info', 'journal_volume'], 
['publication_info', 'journal_issue'], 
['publication_info', 'year'], 		
['publication_info', 'page_start'],	
['publication_info', 'page_end'], 	
['publication_info', 'artid'], 		
['publication_info', 'cnum'], 	
['imprint', 'publisher'], 		
['authors', 'full_name'], 	
['authors', 'inspire role']
