### ISSUE TITLE
Wrong results in affiliations autocompletion

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#200]
When you type "IP" in affiliations, you get irrelevant results in autocompletion:
 <img width="300" alt="screen shot 2017-09-13 at 12 05 08" src="https://user-images.githubusercontent.com/24955201/30371725-bf934be6-987b-11e7-9f50-ef3340fc3c87.png">

**Comment by harunurhan** [comment]
This should be create for `inspire-next` because, we display all the results returned. And also I don't think they are necessarily wrong, since search has been done on more fields than you see on the result items on UI, such as `postcode`. So it could be one of them which matches with IP.

**Comment by StellaCh** [comment]
Then, still, it should show to the user where it found that string, otherwise it looks like a mistake

**Comment by harunurhan** [comment]
@StellaCh well putting all indexed fields on the UI might look too much though. 😟

**Comment by harunurhan** [comment]
https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/398
