### ISSUE TITLE
Preview: update references

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#207]
The list of references is not updated when you click on Save to preview.
Here I erased the first reference:
![ref1](https://user-images.githubusercontent.com/24955201/30551107-b9e36d8a-9c99-11e7-92d3-bda2e239b775.PNG)

but it's not updated in the preview

![ref2](https://user-images.githubusercontent.com/24955201/30551117-c219e7d6-9c99-11e7-9f4e-1f3c9dfe2da8.PNG)

However, the number of references is updated correctly: It used to be 99 and now they both show that there're 98 references

**Comment by harunurhan** [comment]
This is because `citations` and `references` are populated not with the record that is posted to `/previews` but with other `http` request that are fetching stuff from db. Since the db is still not updated during preview, it's not showing the change.

**Comment by harunurhan** [comment]
@jmartinm  https://github.com/inveniosoftware-contrib/invenio-record-editor/issues/22
