### ISSUE TITLE
Refextract problem

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#208]
Refextract does seem to work for any reference.
Example: in https://labs.inspirehep.net/editor/literature/1620910
I clicked on 'Replace existing' and copy-pasted the following text:

> E. Gross and O. Vitells, Trial factors or the look elsewhere effect in high energy physics,
> Eur. Phys. J. C 70 (2010) 525, arXiv: 1005.1891 [physics.data-an].
> [99] ATLAS Collaboration, ATLAS Computing Acknowledgements 2016–2017,
> ATL-GEN-PUB-2016-002, 2016, url: https://cds.cern.ch/record/2202407.

And nothing happened.

**Comment by harunurhan** [comment]
This is not a problem with the UI but probably a problem with `inspire-next`, server returns `500` so and it doesn't say anything else. So Maybe @michamos can have look.

Only thing that might causing this from UI, is that `word-break` on `textarea` putting `↵` unicode to the text.

**Comment by michamos** [comment]
This seems to be an EOS problem when opening the journal KB, not a unicode problem. See  https://sentry.cern.ch/inspire-sentry/inspire-labs/group/865495/

**Comment by harunurhan** [comment]
Ok, then closing this.
