### ISSUE TITLE
Auto-complete support for certain fields

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#21]
For some fields, auto-complete should be supported.

Consider using: http://valor-software.com/ng2-bootstrap/#/typeahead

#### Questions: 

- How to know which fields to autocomplete? @jmartinm @kaplun 
 - I think it should be on the schema, because it would be much easier to implement 😃 , but it may not make sense for the schema.
- How to query elastic-search for autocompletion? by using what end-point? @jmartinm

**Comment by kaplun** [comment]
IMHO the schema could be a natural place. E.g. we can have an: `x-inspire-autocomplete-entrypoint` attribute (to make it clear it's a full extension), which supports a URL.

**Comment by egabancho** [comment]
Hi! `invenio-records-rest` already provides an end-point for suggestion, i.e. https://github.com/inveniosoftware/invenio-records-rest/blob/master/examples/app.py#L78 

You can see an example about the field auto-completion in Zenodo https://github.com/zenodo/zenodo/pull/654/commits/597af1b822da4cb7b654871286d273cd954c082f#diff-17aab5d1e386f3a52d65ab305c335889R297
