### ISSUE TITLE
Show pdf instead of splash page in preview

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#211]
Currently, in preview we see the splash page: 

![pdf1](https://user-images.githubusercontent.com/24955201/30586509-7c258fe0-9d30-11e7-88be-3ad85ee9c703.PNG)

Instead, users need to see directly the pdf: 

![pdf](https://user-images.githubusercontent.com/24955201/30586513-802a795c-9d30-11e7-9425-c7bcfbed1899.PNG)

If I'm not mistaken, this was in place in one of the first versions of the record editor.

**Comment by harunurhan** [comment]
they are different things, current config shows whatever available.

1. pdf - the first url with `.pdf` extension in `urls` field.
2. arXiv - the link to first arXiv Id in `arxiv_eprints` field.
3. doi - the link to first doi in `dois` field

**Comment by StellaCh** [comment]
For arXiv, you should change the config:
If you have https://arxiv.org/abs/1305.4434 , change it to https://arxiv.org/pdf/1305.4434.pdf so that it shows the pdf always

**Comment by harunurhan** [comment]
@StellaCh 
- do all arXiv records have pdf?
- should be like an addition preview  or I remove the preview to arXiv page in favor of this?

**Comment by StellaCh** [comment]
- yes they do
- no need to have them both, only the pdf is needed.

Thanks!
