### ISSUE TITLE
Help modal with cheatsheet

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#220]
- [ ] shortcut cheatsheet (key to action mapping)
- [ ]  link to shortcut action definitions (https://inveniosoftware-contrib.github.io/ng2-json-editor/docs/interfaces/_interfaces_custom_shortcut_keys_.customshortcutkeys.html)
- [ ] `$$` reference splitting cheatsheet (character to path mapping)
- [ ] link to schema documentation https://inspire-schemas.readthedocs.io/en/latest/schemas/records/hep.html

**Comment by StellaCh** [comment]
You can create a modal similar to this: [Keyboard shortcuts.docx](https://github.com/inspirehep/record-editor/files/1333782/Keyboard.shortcuts.docx)

Let's discuss in person how to make some shortcuts' description easier to understand
