### ISSUE TITLE
Show language name instead of iso code

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#225]
In the language dropdown, show the language name instead of the iso code. Users couldn't understand the iso codes:
<img width="163" alt="screen shot 2017-09-28 at 16 14 01" src="https://user-images.githubusercontent.com/24955201/30971425-212f7b16-a468-11e7-85a4-ec130318978e.png">

**Comment by harunurhan** [comment]
Can be implemented when https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/408 is resolved.

**Comment by harunurhan** [comment]
https://www.npmjs.com/package/iso-639-1 could be used for languages. @StellaCh do you have any other enum that you want to put display values?

**Comment by StellaCh** [comment]
That looks good

**Comment by harunurhan** [comment]
closed by  #245
