### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#226]
Add a search bar on top of the tabs. The buttons next to the search bar are hidden by default.
<img width="574" alt="screen shot 2017-09-28 at 16 04 54" src="https://user-images.githubusercontent.com/24955201/30970943-d7a09350-a466-11e7-826d-f91f3e62f711.png">

Features:
- search by record id 
- search by a list of record ids. In that case, the buttons fa-chevron-right and fa-chevron-left appear with tooltips 'Previous record' and 'Next record' <img width="94" alt="screen shot 2017-09-28 at 16 08 57" src="https://user-images.githubusercontent.com/24955201/30971133-65f6a522-a467-11e7-84c2-0adf77c36e8e.png">
- if you click on fa-chevron-right and you haven't made any modifications on the record, it goes to the next record in the list
- if you click on the button and you have made a modification, then the same functionality as 'Save' is triggered: the preview modal appears and user has to click on 'Confirm' to move to the next record

**Comment by harunurhan** [comment]
@StellaCh  @jmartinm 

So searching is only by record id?

**Comment by StellaCh** [comment]
Searching by record id is the priority and the most usual use case, so that should be there for the 1st version.
If it's quick to add all inspire search, then that's good. If it's complicated, leave it for the next version.

**Comment by harunurhan** [comment]
Adding inspire search is not a problem, since we have already backend for this. But I don't know it supports searching by recid. @jmartinm ? 

More importantly the problem would be that it might return a lot of results and all of them might not be the records that cataloger wants, compared to precise results returned for the list of record ids.
