### ISSUE TITLE
SPIRES syntax in the search field

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#250]
The search in the record editor doesn't work with SPIRES syntax - although the query parser supports that:
<img width="436" alt="screen shot 2017-11-15 at 14 14 30" src="https://user-images.githubusercontent.com/24955201/32837896-91f83780-ca0f-11e7-894e-ae92a3d6a354.png">

but it works without SPIRES keywords:
<img width="437" alt="screen shot 2017-11-15 at 14 15 03" src="https://user-images.githubusercontent.com/24955201/32837911-99eac2c8-ca0f-11e7-9017-0c6f73afa049.png">

The curators would need to use SPIRES syntax too.

**Comment by harunurhan** [comment]
@StellaCh this doesn't seem to work on inspire-next so I'll move this to inspire-next, if that's OK?

See: https://qa.inspirehep.net/search?page=1&size=25&cc=literature&q=find%20a%20moskovic

**Comment by harunurhan** [comment]
this is fixed by https://github.com/inspirehep/inspire-utils/pull/25, not deployed yet.
