### ISSUE TITLE
Error when uploading pdf in url 

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#252]
I tried to fill in the `documents`.`url` field with a pdf:

<img width="708" alt="screen shot 2017-11-15 at 14 50 05" src="https://user-images.githubusercontent.com/24955201/32839330-608ba452-ca14-11e7-90c2-cfa318d34c72.png">

but when trying to save, I got this error:
<img width="262" alt="screen shot 2017-11-15 at 14 52 26" src="https://user-images.githubusercontent.com/24955201/32839395-92f50316-ca14-11e7-8fba-e51a97cfd9ad.png">

The test pdf was https://www.researchgate.net/profile/Hiller_Spires/publication/237439677_The_Case_for_Social_Agency_in_Computer-Based_Teaching_Do_Students_Learn_More_Deeply_When_They_Interact_With_Animated_Pedagogical_Agents/links/5697b9ae08aec79ee32b46ae.pdf

**Comment by harunurhan** [comment]
This error definitely nothing to do with `record-editor`, so I'll move this to `inspire-next` after doing some investigation to get what the error is about.

**Comment by harunurhan** [comment]
actually this works for me but I don't know how different is the `qa` from `master` of `inspire-next`. So I am closing this, if it happens all the time or again please create an issue on `inspire-next` repo.

@StellaCh
