### ISSUE TITLE
Save before manual merge

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#270]
As a user, when I edit a record and then click on the manual merger icon, I want my changes to be saved before I merge the record.
Solution: The editor should save the record first before doing the manual merging

**Comment by harunurhan** [comment]
Should saving be done with a preview modal like (clicking the save button) or we should just save the record without previewing?

**Comment by StellaCh** [comment]
Save without preview when you click on manual merging. Then, when you make the merge and click on save in the holding pen, then you should see a preview of the merged record.
