### ISSUE TITLE
No error panel when loading a record

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#275]
When I open the record https://qa.inspirehep.net/editor/literature/1630823 , I see that there are errors but the error panel is empty: ![errors](https://user-images.githubusercontent.com/24955201/34042835-caeee51a-e19e-11e7-999c-d766d9cc0160.PNG)

Instead, when I click on Save, the error panel finally appears

**Comment by harunurhan** [comment]
https://github.com/inspirehep/record-editor/pull/280/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R43 change will fix this, I think but needs to be verified of course.

**Comment by StellaCh** [comment]
Still happening in https://qa.inspirehep.net/editor/literature/42946

**Comment by harunurhan** [comment]
That's is normal for now, after next deployment I will check it.

**Comment by harunurhan** [comment]
fixed
