### ISSUE TITLE
Manual merge: 'Reject all' adds duplicate entries

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#276]
Bugs when I do a manual merge and I select 'Reject all':

1. The editor creates duplicate conflicts instead of resolving them.
2. The conflicts in the error panel are 0, but they still show in the list below
3. The buttons 'Reject all' and 'Accept all' should disappear 

![reject](https://user-images.githubusercontent.com/24955201/34149918-10347206-e4a7-11e7-8e03-faa53621706b.PNG)

**Comment by harunurhan** [comment]
Can you check all those issue on `qa` and confirm they aren't resolved @StellaCh

**Comment by StellaCh** [comment]
still a problem in https://qa.inspirehep.net/editor/holdingpen/836377

**Comment by harunurhan** [comment]
Mentioned issues are also fixed by several PRs on `ng2-json-editor`

https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/450
https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/451
