### ISSUE TITLE
Empty error panel

### ISSUE THREAD

**Issue by StellaCh** [inspirehep/record-editor#277]
When I click on a field with a conflict and then click on the error panel, the error panel appears totally empty. It should show the list of conflicts and errors.

![merge](https://user-images.githubusercontent.com/24955201/34150166-d3162152-e4a7-11e7-912f-e0742510bc1b.PNG)

When I click again on `number of pages`, the contents of the error panel appear correctly.

**Comment by harunurhan** [comment]
Can you also verify if still happens on qa @StellaCh .

**Comment by StellaCh** [comment]
still happens in https://qa.inspirehep.net/editor/holdingpen/836377

**Comment by harunurhan** [comment]
fixed by https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/450
