### ISSUE TITLE
Show warnings of author extraction

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#284]
To implement after https://github.com/inspirehep/inspire-next/pull/3092 is merged.

I guess using toast message would be enough? @StellaCh @michamos

**Comment by StellaCh** [comment]
What type of warnings are they @michamos ? It might be worth using the error panel if it's appropriate

**Comment by michamos** [comment]
How long do these toast messages stay visible? there can be several warnings that the curator has to check, so if they stay only a few seconds it's too short.

**Comment by michamos** [comment]
> It might be worth using the error panel if it's appropriate

:+1: Error panel seems more appropriate.

**Comment by harunurhan** [comment]
@michamos toasts can be visible forever with or without hide button (x).

At the moment whatever you put bottom console's `Warnings` tab, it's going to stay there unless it is cleared programmatically. So if you don't want them to stay there all time we have to decide on a logic to clear it, such as "it's cleared when author extract used next time"

**Comment by ksachs** [comment]
for https://labs.inspirehep.net/tools/authorlist
it can be added to the normal output - which is to be used cut and paste anyhow.
Would be nice it this can be done fast, so catalogers can use it:

    [here go the warnings]
    
    --------------------------------------------------------
    
    [here goes the marc-xml output]


For the integration in the new editor I don't know how the various possibilities would look like.

**Comment by michamos** [comment]
@ksachs this is about the new record editor. For the current tool, I have integrated the warnings in inspirehep/inspire-next#3092. but it's waiting for a review and merge. I have put the warnings under the MARC output, but it's a good idea to invert that to make the warnings more visible.
