### ISSUE TITLE
make sidebar collapsable

### ISSUE THREAD

**Issue by drjova** [inspirehep/record-editor#295]
The sidebar takes a lot of space, the idea is to make it collapsable (by default collapsed).

<img width="322" alt="screen shot 2018-01-16 at 23 08 26" src="https://user-images.githubusercontent.com/4287772/35015175-754f5534-fb13-11e7-84db-83539bd0ec7b.png">

**Comment by harunurhan** [comment]
I think, there is a plan for bigger redesign which includes this as well. So I think better not to implement this separately

@StellaCh

**Comment by StellaCh** [comment]
This is the 1st step of the editor redesign as discussed with @drjova @harunurhan and @Dinika and has been requested by users repeatedly, especially by @cleggm1, so it would be a very nice improvement

**Comment by drjova** [comment]
Supersede by https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/455
