### ISSUE TITLE
Support hidden fields/subfields

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#31]
Any property that has `x_editor_hidden` set, shouldn't be on the UI.

This can be implemented by deleting properties from the record if `x_editor_hidden` is set for them in the schema.

**Comment by jmartinm** [comment]
Some fields that can be removed from the UI:

* [ ] curated_relation
* [ ] inspire_bai
* [ ] uuid

Some other ones will disappear when https://github.com/inspirehep/inspire-next/pull/1291 is merged.
