### ISSUE TITLE
Support disabled fields/subfields

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#32]
Any property that has `x_editor_disabled` set, shouldn't be editable on the UI.

**Comment by harunurhan** [comment]
still not sure if we have a use case for this one, @jmartinm.

**Comment by jmartinm** [comment]
> Any property that has x_editor_hidden set, shouldn't be editable on the UI.

`x_editor_disabled` I guess.

**Comment by jmartinm** [comment]
@annetteholtkamp 

Any known case where we would like to have a field visible in the interface but not-editable?

**Comment by annetteholtkamp** [comment]
One example are the texkeys - which one should be able to move somewhere else (as deprecated), but not modify them.
Another is the cnum in conference records.

One could think of others. Probably arXiv nrs shouldn’t be changeable. Or the raw affiliation strings or raw reference strings.
Or primarch (the primary arxiv category currently in 035. Or the arXiv categories in 65017.

- Annette

**Comment by harunurhan** [comment]
@jmartinm 
For disabled fields, should we create a new component since we won't be using 2 way binding,  and`<input>`, also in that case we will be able to customize the look of disabled fields.

Or should we just set `disabled` of the element (might be `input - number, input - text etc.`) which holds the disabled field.
