### ISSUE TITLE
Support selecting another subfield name for a value

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#34]
Allow selecting another subfield name from the ones that are in schema but not present in the record, for a value that is in the record.

We should decide if we want to allow it for all properties of all objects, or all properties of selected objects, or selected properties of selected objects.

We can use `x_editor_allow_key_change` in the schema to specify if we need don't want to allow it for all.

**Comment by jmartinm** [comment]
@annetteholtkamp Can you mention some current use cases where nowadays a change of subfield name is done on a record?

That way we can see if it is a rare situation (in which case we can allow only on certain fields) or more common.

We would like to avoid cluttering the interface with buttons and avoid error prone operations like this kind of change of subfield label if it is not needed.

If, for example, this is needed in reference fields we can add it to those.

**Comment by annetteholtkamp** [comment]
I do it quite often in references. E.g. when a report number or journal publication info is not recognised and put into the $$m subfield.
Another case is the bibtex key. If upon first ingestion an author is badly mangled a weird texkey is generated. I now move it into $$z and a new $$a is generated by the system.
I also do it when by mistake I’ve added something in the wrong subfield - it easily happens that one confuses neighbouring lines.. Then I just change the subfield.
Another use case is the journal info in 773. Sometimes our system has problems differentiating between volume, issue and page/article id. It’s handy if one can just rename the subfields. 

If I think a bit longer I’ll probably come up with more cases :-)

- Annette

**Comment by harunurhan** [comment]
Issue moved to [inspirehep/ng2-json-editor #7](https://github.com/inspirehep/ng2-json-editor/issues/7) via [**ZenHub**](https://www.zenhub.com/)
