### ISSUE TITLE
Create invenio backend for the app

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#36]
An invenio based server app should be created to provide web services that editor needs and serve the editor itself.

**Comment by jmartinm** [comment]
API should support at the start:

* [ ] Save record - will save the JSON into the Database.
* [ ] Delete record - will mark the record as deleted.
* [ ] Validate record - will run custom code (validators) on the JSON and return a structure the editor can understand (see https://github.com/inspirehep/ng2-json-editor/blob/master/example/assets/mock-data/remote-validation-response.json)

After we will add functionalities to interact with other modules and merge 2 records.

**Comment by jmartinm** [comment]
moved to https://github.com/inspirehep/invenio-record-editor/issues/2
