### ISSUE TITLE
Unify display of array of objects and array with array inside.

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#40]
Currently there are two different ways of displaying fields depending on the data type inside:

![screen shot 2016-07-28 at 1 08 45 pm](https://cloud.githubusercontent.com/assets/580727/17210687/91d02608-54c4-11e6-9c8b-30738bce0dd5.png)

We should try to unify them to make the interface less confusing. A proposal is to display arrays as different inputs inside of the table:

<img width="1220" alt="array inside of array ob objects" src="https://cloud.githubusercontent.com/assets/580727/17210712/b7882e04-54c4-11e6-8d9d-685fc4e6f54a.png">

We can have:

* A small plus button close to the last element to add a new one.
* Further on, a drag and drop handle to move them in the Array (if needed)

**Comment by harunurhan** [comment]
Solved by #54
