### ISSUE TITLE
Create stub tests for all components

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#48]
Coverage only takes into account files loaded in *.spec files. (https://coveralls.io/github/inspirehep/record-editor)

For each component, create a basic test that loads the component so that we can see the real coverage of the app.

**Comment by harunurhan** [comment]
Issue moved to [inspirehep/ng2-json-editor #8](https://github.com/inspirehep/ng2-json-editor/issues/8) via [**ZenHub**](https://www.zenhub.com/)
