### ISSUE TITLE
Investigate angular2 change detection and re-rendering

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#56]
While working on something else, I realised that angular might be re-rendering some components whose model not changed.

So we should investigate this and optimize the code in order to minimize the UI update to the single component so that we don't  performance issues for big records.

**Comment by harunurhan** [comment]
It is probably a good idea to consider using `Immutables` and `Observables` to avoid checking components that aren't changed.

[This article](https://vsavkin.com/change-detection-in-angular-2-4f216b855d4c#.fh4ipmjco) gives the basic info how to do that and explains how it improves the performance.

**Comment by jmartinm** [comment]
We have now seen that `Immutables` indeed improve performance considerably.
