### ISSUE TITLE
Additional schema-specific configuration support

### ISSUE THREAD

**Issue by kaplun** [inspirehep/record-editor#63]
Currently #62 and other branches have introduced special `x-editor-*` properties that are expected to be stored in the corresponding JSONSchema.

As discussed IRL, this is not ideal because it mixes the data model with UI specificities. A proposed solution is to have the editor to load a second JSON that is going to be merged with the current schema, so that these additional properties can still refer to specific fields without impacting the original schema.

cc: @jacquerie

**Comment by harunurhan** [comment]
Issue moved to [inspirehep/ng2-json-editor #11](https://github.com/inspirehep/ng2-json-editor/issues/11) via [**ZenHub**](https://www.zenhub.com/)
