### ISSUE TITLE
Bundle or not to bundle the web application

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/record-editor#64]
Now everything is mixed in this repository, both web application that uses `editor` for inspire-next and core`editor` component are being developed together. However our plan is to separate these.

When we separate it, it is clear that we will not bundle, minify, uglify etc. the core `editor`  before publishing to npm. However i am not sure if we should keep using webpack for bundling the web application.

Because I think it might be bundled again with all parts of inspire-next which is not good since we may end up duplicate dependencies.

cc @jmartinm

**Comment by jmartinm** [comment]
We are currently bundling `record-editor` so this can be closed.
