### ISSUE TITLE
Validators to implement

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/record-editor#78]
Here we can keep track of all the complex validators (dependent on INSPIRE data model) that can be implemented and that should issue either warnings or errors.

The validation might be implemented on the Python side and the editor will just call the URL to get the validation warnings.

Errors
=======

Warnings
=======

* [ ] In the `publication_information` field, 2 cnums are possible in rare situations. Having 2 cnums should trigger a warning.

**Comment by harunurhan** [comment]
Issue moved to [inspirehep/ng2-json-editor #1](https://github.com/inspirehep/ng2-json-editor/issues/1) via [**ZenHub**](https://www.zenhub.com/)
